FROM oven/bun:1.3.14 AS build

WORKDIR /app

COPY package.json bun.lock ./
COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
COPY packages/db/package.json packages/db/package.json
COPY packages/types/package.json packages/types/package.json

RUN bun install --frozen-lockfile

COPY . .
ARG VITE_API_BASE_URL_PROD=https://auto-collection.dafengchan.top/api/v1
ENV VITE_API_BASE_URL_PROD=${VITE_API_BASE_URL_PROD}
ARG VITE_API_BASE_URL=https://auto-collection.dafengchan.top/api/v1
ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
RUN bun --filter @app/web build

FROM nginx:1.27-alpine

COPY deploy/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/apps/web/dist /usr/share/nginx/html

EXPOSE 80
