"use strict";

var contract = require("./action-contract.js");

function createScreenActions(deps, layout) {
  deps = deps || {};
  if (!layout) throw new Error("screen layout is required");
  function stop() { try { return deps.shouldStop && deps.shouldStop() ? contract.stopped() : null; } catch (error) { return contract.failure(contract.REASON.STOP_CHECK_FAILED, "stop check failed"); } }
  function dependency(names, args, message) { for (var i = 0; i < names.length; i += 1) if (typeof deps[names[i]] === "function") { try { return contract.success(deps[names[i]].apply(deps, args || [])); } catch (error) { return contract.failure(contract.REASON.DRIVER_ERROR, message + " failed"); } } return contract.failure(contract.REASON.DEPENDENCY_MISSING, message + " missing"); }
  function now() { var result = dependency(["now"], [], "time source"); if (!result.success) return result; return typeof result.value === "number" && isFinite(result.value) ? result : contract.failure(contract.REASON.TIME_SOURCE_ERROR, "time source returned invalid value"); }
  function sleepFor(milliseconds) { var stopped = stop(); if (stopped) return stopped; if (typeof deps.sleep !== "function") return contract.failure(contract.REASON.DEPENDENCY_MISSING, "sleep dependency missing"); try { if (deps.sleep(milliseconds) === false) return contract.failure(contract.REASON.SLEEP_ERROR, "sleep returned false"); } catch (error) { return contract.failure(contract.REASON.SLEEP_ERROR, "sleep failed"); } stopped = stop(); return stopped || contract.success(milliseconds); }
  function waitForNode(selector, timeoutMs) {
    var stopped = stop(); if (stopped) return stopped; var defaults = layout.WAIT_OPTIONS || {}, timeout = Math.max(0, Math.floor(typeof timeoutMs === "number" && isFinite(timeoutMs) ? timeoutMs : defaults.timeoutMs || 5000));
    var interval = Math.max(1, Math.floor(defaults.pollIntervalMs || 200)), attempts = Math.max(1, Math.floor(timeout / interval) + 1), start = now(); if (!start.success) return start;
    for (var i = 0; i < attempts; i += 1) { stopped = stop(); if (stopped) return stopped; var found = dependency(["findNode", "lookupNode", "find"], [selector], "node lookup"); if (!found.success) return contract.failure(contract.REASON.NODE_LOOKUP_FAILED, found.message); stopped = stop(); if (stopped) return stopped; if (found.value) return found; if (i + 1 >= attempts) break; var current = now(); if (!current.success) return current; if (Math.max(0, current.value - start.value) >= timeout) break; var slept = sleepFor(Math.min(interval, timeout - Math.max(0, current.value - start.value))); if (!slept.success) return slept; }
    return contract.failure(contract.REASON.NODE_TIMEOUT, "node wait timed out");
  }
  function readValue(node, key) { try { var value = node && node[key]; value = typeof value === "function" ? value.call(node) : value; return contract.success(value === null || typeof value === "undefined" ? "" : String(value)); } catch (error) { return contract.failure(contract.REASON.NODE_READ_FAILED, "node " + key + " read failed"); } }
  function readText(selector, timeoutMs) { var found = waitForNode(selector, timeoutMs); if (!found.success) return found; var text = readValue(found.value, "text"); if (text.success && text.value.trim()) return text; var desc = readValue(found.value, "desc"); if (desc.success && desc.value.trim()) return desc; return !text.success ? text : !desc.success ? desc : contract.failure(contract.REASON.NODE_TEXT_UNAVAILABLE, "node has no text or description"); }
  function readSize(snapshot) { try { var source = snapshot && typeof snapshot.width === "number" && typeof snapshot.height === "number" ? snapshot : (typeof deps.screenSize === "function" ? deps.screenSize() : deps.screenSize); return contract.success(layout.normalizeScreenSize(source)); } catch (error) { return contract.failure(contract.REASON.SCREEN_CAPTURE_FAILED, "screen size read failed"); } }
  function recycle(image) { try { if (typeof deps.recycleImage === "function") deps.recycleImage(image); else if (image && typeof image.recycle === "function") image.recycle(); return contract.success(); } catch (error) { return contract.failure(contract.REASON.IMAGE_RECYCLE_FAILED, "image recycle failed"); } }
  function processRegion(image, region) { var clip, result, recycled = contract.success(); try { clip = deps.clipImage(image, region); if (!clip) result = contract.failure(contract.REASON.OCR_FAILED, "image clip failed"); else { var stopped = stop(); if (stopped) result = stopped; else { var raw = deps.recognize(clip, region); stopped = stop(); result = stopped || contract.success({ name: region.name, region: region, value: typeof deps.parseOcr === "function" ? deps.parseOcr(raw, region) : raw }); } } } catch (error) { result = contract.failure(contract.REASON.OCR_FAILED, "ocr processing failed"); } finally { if (clip) recycled = recycle(clip); } return result && !result.success ? result : recycled.success ? result : recycled; }
  function processRegions(image, snapshot, regions) { var size = readSize(snapshot); if (!size.success) return size; var requested = regions == null ? layout.getCaptureRegions(size.value) : (Array.isArray(regions) ? regions : [regions]); var resolved = []; for (var i = 0; i < requested.length; i += 1) { var region = layout.resolveRegion(requested[i], size.value); if (!region) return contract.failure(contract.REASON.OCR_FAILED, "unknown capture region"); resolved.push(region); } if (typeof deps.clipImage !== "function" || typeof deps.recognize !== "function") return contract.failure(contract.REASON.DEPENDENCY_MISSING, "clip or recognize dependency missing"); var values = []; for (var j = 0; j < resolved.length; j += 1) { var stopped = stop(); if (stopped) return stopped; var processed = processRegion(image, resolved[j]); if (!processed.success) return processed; values.push(processed.value); } return contract.success(values); }
  function captureRegions(regions) { var stopped = stop(); if (stopped) return stopped; var captured = dependency(["captureScreen", "takeScreenshot"], [], "screen capture"); if (!captured.success) return contract.failure(contract.REASON.SCREEN_CAPTURE_FAILED, captured.message); var snapshot = captured.value, image = snapshot && Object.prototype.hasOwnProperty.call(snapshot, "image") ? snapshot.image : snapshot; stopped = stop(); if (!image) return stopped || contract.failure(contract.REASON.SCREEN_CAPTURE_FAILED, "screen capture returned no image"); var result; try { result = processRegions(image, snapshot, regions); } catch (error) { result = contract.failure(contract.REASON.OCR_FAILED, "ocr processing failed"); } var recycled = recycle(image); return !recycled.success && result.success ? recycled : result; }
  function diagnostic(names) { var stopped = stop(); if (stopped) return stopped; var result = dependency(names, [], "verification diagnostics"); stopped = stop(); return stopped || result; }
  function riskDetected(value) { return value === true || !!(value && typeof value === "object" && (value.detected === true || value.verification === true || value.reason === contract.REASON.PLATFORM_VERIFICATION)); }
  function detectPlatformVerification() { var stopped = stop(); if (stopped) return stopped; var risk = dependency(["detectRisk", "detectPlatformRisk", "detectVerification"], [layout.SELECTOR_DESCRIPTIONS && layout.SELECTOR_DESCRIPTIONS.platformVerification], "platform verification detector"); if (!risk.success) return contract.failure(contract.REASON.VERIFICATION_CHECK_FAILED, risk.message); stopped = stop(); if (stopped) return stopped; var page = diagnostic(["getPageStructure", "readPageStructure"]); if (!page.success) return page; var trace = diagnostic(["getActionTrace", "readActionTrace"]); if (!trace.success) return trace; var details = { risk: risk.value, pageStructure: page.value, actionTrace: trace.value }; return riskDetected(risk.value) ? contract.failure(contract.REASON.PLATFORM_VERIFICATION, "platform verification detected", details) : contract.success(details); }
  return { waitForNode: waitForNode, readText: readText, captureRegions: captureRegions, detectPlatformVerification: detectPlatformVerification };
}
module.exports = { createScreenActions: createScreenActions };
