COMMENT ON TABLE "collector_devices" IS '手机采集设备表，记录每台运行 Auto.js 脚本的手机设备和最后心跳状态';
COMMENT ON COLUMN "collector_devices"."id" IS '设备主键 UUID';
COMMENT ON COLUMN "collector_devices"."device_code" IS '设备业务编号，手机脚本上报的 deviceId';
COMMENT ON COLUMN "collector_devices"."device_name" IS '设备显示名称，默认等于设备业务编号';
COMMENT ON COLUMN "collector_devices"."platform" IS '采集平台，例如 douyin';
COMMENT ON COLUMN "collector_devices"."app_version" IS '手机脚本或采集应用版本号';
COMMENT ON COLUMN "collector_devices"."status" IS '设备上报状态：online/running/paused/error/offline';
COMMENT ON COLUMN "collector_devices"."last_heartbeat_at" IS '最后一次心跳上报时间';
COMMENT ON COLUMN "collector_devices"."tenant_id" IS '租户编号，当前默认 default';
COMMENT ON COLUMN "collector_devices"."created_at" IS '创建时间';
COMMENT ON COLUMN "collector_devices"."updated_at" IS '更新时间';
COMMENT ON COLUMN "collector_devices"."created_by" IS '创建人或创建来源';
COMMENT ON COLUMN "collector_devices"."updated_by" IS '更新人或更新来源';
COMMENT ON COLUMN "collector_devices"."deleted_at" IS '软删除时间';

COMMENT ON TABLE "collection_tasks" IS '采集任务配置表，记录视频/直播采集时长、搜索词、匹配词等配置';
COMMENT ON COLUMN "collection_tasks"."id" IS '任务主键 UUID';
COMMENT ON COLUMN "collection_tasks"."task_code" IS '任务业务编号，手机脚本上报的 taskId';
COMMENT ON COLUMN "collection_tasks"."name" IS '任务名称';
COMMENT ON COLUMN "collection_tasks"."platform" IS '采集平台，例如 douyin';
COMMENT ON COLUMN "collection_tasks"."mode" IS '采集模式：search/feed';
COMMENT ON COLUMN "collection_tasks"."search_keywords" IS '搜索关键词数组';
COMMENT ON COLUMN "collection_tasks"."match_keywords" IS '农业内容匹配关键词数组';
COMMENT ON COLUMN "collection_tasks"."video_minutes_min" IS '视频阶段每日随机最小时长，单位分钟';
COMMENT ON COLUMN "collection_tasks"."video_minutes_max" IS '视频阶段每日随机最大时长，单位分钟';
COMMENT ON COLUMN "collection_tasks"."live_minutes_min" IS '直播阶段每日随机最小时长，单位分钟';
COMMENT ON COLUMN "collection_tasks"."live_minutes_max" IS '直播阶段每日随机最大时长，单位分钟';
COMMENT ON COLUMN "collection_tasks"."collect_comments" IS '是否采集视频评论';
COMMENT ON COLUMN "collection_tasks"."comment_limit" IS '每条视频最多采集评论数';
COMMENT ON COLUMN "collection_tasks"."heartbeat_minutes" IS '手机脚本心跳间隔，单位分钟';
COMMENT ON COLUMN "collection_tasks"."status" IS '任务状态：DRAFT/ENABLED/DISABLED';
COMMENT ON COLUMN "collection_tasks"."tenant_id" IS '租户编号，当前默认 default';
COMMENT ON COLUMN "collection_tasks"."created_at" IS '创建时间';
COMMENT ON COLUMN "collection_tasks"."updated_at" IS '更新时间';
COMMENT ON COLUMN "collection_tasks"."created_by" IS '创建人或创建来源';
COMMENT ON COLUMN "collection_tasks"."updated_by" IS '更新人或更新来源';
COMMENT ON COLUMN "collection_tasks"."deleted_at" IS '软删除时间';

COMMENT ON TABLE "collection_records" IS '采集记录表，保存手机脚本识别到的农业视频或直播关键信息';
COMMENT ON COLUMN "collection_records"."id" IS '采集记录主键 UUID';
COMMENT ON COLUMN "collection_records"."task_id" IS '关联采集任务主键';
COMMENT ON COLUMN "collection_records"."device_id" IS '关联采集设备主键';
COMMENT ON COLUMN "collection_records"."platform" IS '采集平台，例如 douyin';
COMMENT ON COLUMN "collection_records"."scene_type" IS '采集阶段或内容类型：video/live';
COMMENT ON COLUMN "collection_records"."keyword" IS '触发搜索或采集的关键词';
COMMENT ON COLUMN "collection_records"."matched_keywords" IS '命中的农业关键词数组';
COMMENT ON COLUMN "collection_records"."author_name" IS '作者、主播或账号名称';
COMMENT ON COLUMN "collection_records"."title_text" IS '标题、直播间标题或主文案';
COMMENT ON COLUMN "collection_records"."subtitle_text" IS '辅助文案、摘要或补充文本';
COMMENT ON COLUMN "collection_records"."metrics_text" IS '点赞、评论、在线人数、人气等指标文本';
COMMENT ON COLUMN "collection_records"."hot_comments_json" IS '热视频评论数组 JSON';
COMMENT ON COLUMN "collection_records"."screen_text" IS '当次屏幕 OCR/控件文本全集';
COMMENT ON COLUMN "collection_records"."raw_payload" IS '手机脚本原始上报载荷';
COMMENT ON COLUMN "collection_records"."captured_at" IS '手机端采集发生时间';
COMMENT ON COLUMN "collection_records"."tenant_id" IS '租户编号，当前默认 default';
COMMENT ON COLUMN "collection_records"."created_at" IS '创建时间';
COMMENT ON COLUMN "collection_records"."updated_at" IS '更新时间';
COMMENT ON COLUMN "collection_records"."created_by" IS '创建人或创建来源';
COMMENT ON COLUMN "collection_records"."updated_by" IS '更新人或更新来源';
COMMENT ON COLUMN "collection_records"."deleted_at" IS '软删除时间';

COMMENT ON TABLE "device_heartbeats" IS '设备心跳表，记录手机脚本运行阶段、计数、剩余时长和最后消息';
COMMENT ON COLUMN "device_heartbeats"."id" IS '心跳主键 UUID';
COMMENT ON COLUMN "device_heartbeats"."task_id" IS '关联采集任务主键';
COMMENT ON COLUMN "device_heartbeats"."device_id" IS '关联采集设备主键';
COMMENT ON COLUMN "device_heartbeats"."status" IS '手机脚本状态：online/running/paused/error/offline';
COMMENT ON COLUMN "device_heartbeats"."scene_type" IS '当前阶段：video/live';
COMMENT ON COLUMN "device_heartbeats"."elapsed_minutes" IS '当前阶段已运行分钟数';
COMMENT ON COLUMN "device_heartbeats"."remaining_minutes" IS '当前阶段剩余分钟数';
COMMENT ON COLUMN "device_heartbeats"."viewed_count" IS '视频阶段已浏览数量';
COMMENT ON COLUMN "device_heartbeats"."live_viewed_count" IS '直播阶段已扫描候选数量';
COMMENT ON COLUMN "device_heartbeats"."live_room_entered_count" IS '直播阶段已进入直播间数量';
COMMENT ON COLUMN "device_heartbeats"."live_candidate_count" IS '直播阶段通过评分的候选数量';
COMMENT ON COLUMN "device_heartbeats"."live_rejected_count" IS '直播阶段未进入的候选数量';
COMMENT ON COLUMN "device_heartbeats"."captured_count" IS '累计保存采集记录数量';
COMMENT ON COLUMN "device_heartbeats"."last_message" IS '手机脚本最后状态消息';
COMMENT ON COLUMN "device_heartbeats"."expected_end_at" IS '当前阶段预计结束时间';
COMMENT ON COLUMN "device_heartbeats"."raw_payload" IS '手机脚本原始心跳载荷';
COMMENT ON COLUMN "device_heartbeats"."reported_at" IS '手机端上报时间';
COMMENT ON COLUMN "device_heartbeats"."tenant_id" IS '租户编号，当前默认 default';
COMMENT ON COLUMN "device_heartbeats"."created_at" IS '创建时间';
COMMENT ON COLUMN "device_heartbeats"."updated_at" IS '更新时间';
COMMENT ON COLUMN "device_heartbeats"."created_by" IS '创建人或创建来源';
COMMENT ON COLUMN "device_heartbeats"."updated_by" IS '更新人或更新来源';
COMMENT ON COLUMN "device_heartbeats"."deleted_at" IS '软删除时间';

COMMENT ON TABLE "runtime_logs" IS '运行日志表，保存手机脚本上报的结构化日志和异常信息';
COMMENT ON COLUMN "runtime_logs"."id" IS '日志主键 UUID';
COMMENT ON COLUMN "runtime_logs"."task_id" IS '关联采集任务主键';
COMMENT ON COLUMN "runtime_logs"."device_id" IS '关联采集设备主键';
COMMENT ON COLUMN "runtime_logs"."level" IS '日志级别：INFO/WARN/ERROR';
COMMENT ON COLUMN "runtime_logs"."message" IS '日志消息';
COMMENT ON COLUMN "runtime_logs"."context_json" IS '结构化日志上下文 JSON';
COMMENT ON COLUMN "runtime_logs"."stop_reason" IS '任务停止原因';
COMMENT ON COLUMN "runtime_logs"."reported_at" IS '手机端上报时间';
COMMENT ON COLUMN "runtime_logs"."tenant_id" IS '租户编号，当前默认 default';
COMMENT ON COLUMN "runtime_logs"."created_at" IS '创建时间';
COMMENT ON COLUMN "runtime_logs"."updated_at" IS '更新时间';
COMMENT ON COLUMN "runtime_logs"."created_by" IS '创建人或创建来源';
COMMENT ON COLUMN "runtime_logs"."updated_by" IS '更新人或更新来源';
COMMENT ON COLUMN "runtime_logs"."deleted_at" IS '软删除时间';

COMMENT ON TABLE "mobile_commands" IS '手机脚本控制指令表，后台下发启动、暂停、恢复、停止、刷新配置等命令';
COMMENT ON COLUMN "mobile_commands"."id" IS '控制指令主键 UUID';
COMMENT ON COLUMN "mobile_commands"."task_id" IS '关联任务主键，可为空';
COMMENT ON COLUMN "mobile_commands"."device_id" IS '目标设备主键';
COMMENT ON COLUMN "mobile_commands"."command_type" IS '指令类型：START/PAUSE/RESUME/STOP/REFRESH_CONFIG/STATUS';
COMMENT ON COLUMN "mobile_commands"."status" IS '指令状态：PENDING/FETCHED/DONE/FAILED/IGNORED';
COMMENT ON COLUMN "mobile_commands"."payload_json" IS '指令参数 JSON';
COMMENT ON COLUMN "mobile_commands"."result_json" IS '手机脚本执行结果 JSON';
COMMENT ON COLUMN "mobile_commands"."issued_at" IS '后台下发时间';
COMMENT ON COLUMN "mobile_commands"."fetched_at" IS '手机脚本拉取时间';
COMMENT ON COLUMN "mobile_commands"."acknowledged_at" IS '手机脚本回执时间';
COMMENT ON COLUMN "mobile_commands"."expires_at" IS '指令过期时间';
COMMENT ON COLUMN "mobile_commands"."tenant_id" IS '租户编号，当前默认 default';
COMMENT ON COLUMN "mobile_commands"."created_at" IS '创建时间';
COMMENT ON COLUMN "mobile_commands"."updated_at" IS '更新时间';
COMMENT ON COLUMN "mobile_commands"."created_by" IS '创建人或创建来源';
COMMENT ON COLUMN "mobile_commands"."updated_by" IS '更新人或更新来源';
COMMENT ON COLUMN "mobile_commands"."deleted_at" IS '软删除时间';
