COMMENT ON TABLE "device_log_files" IS '手机端完整日志文件表，保存 AutoX.js 脚本上传的每日完整运行日志内容和日志统计信息';
COMMENT ON COLUMN "device_log_files"."id" IS '完整日志文件主键 UUID';
COMMENT ON COLUMN "device_log_files"."device_id" IS '关联采集设备主键，标识日志来源手机';
COMMENT ON COLUMN "device_log_files"."task_id" IS '关联采集任务主键，可为空';
COMMENT ON COLUMN "device_log_files"."log_date" IS '日志归属日期，格式 YYYY-MM-DD，用于按天归档查看';
COMMENT ON COLUMN "device_log_files"."file_name" IS '手机端原始日志文件名';
COMMENT ON COLUMN "device_log_files"."content" IS '完整日志文本内容，可能经过手机端上传大小限制截取';
COMMENT ON COLUMN "device_log_files"."file_size_bytes" IS '上传日志文本大小，单位字节';
COMMENT ON COLUMN "device_log_files"."info_count" IS '日志文件内 INFO 级别日志行数';
COMMENT ON COLUMN "device_log_files"."warn_count" IS '日志文件内 WARN 级别日志行数';
COMMENT ON COLUMN "device_log_files"."error_count" IS '日志文件内 ERROR 级别日志行数';
COMMENT ON COLUMN "device_log_files"."last_error_reason" IS '日志文件中最后一条 WARN/ERROR 摘要，用于列表快速定位异常原因';
COMMENT ON COLUMN "device_log_files"."uploaded_at" IS '手机端上传完整日志的时间';
COMMENT ON COLUMN "device_log_files"."tenant_id" IS '租户编号，当前默认 default';
COMMENT ON COLUMN "device_log_files"."created_at" IS '记录创建时间';
COMMENT ON COLUMN "device_log_files"."updated_at" IS '记录更新时间';
COMMENT ON COLUMN "device_log_files"."created_by" IS '创建人或创建来源';
COMMENT ON COLUMN "device_log_files"."updated_by" IS '更新人或更新来源';
COMMENT ON COLUMN "device_log_files"."deleted_at" IS '软删除时间';
